import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import './globals.css';
import { UserProvider } from "@/contexts/UserContext";
import PrelineScript from "@/components/PrelineScript";

export const metadata = {
  title: 'dSign',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
     <PrelineScript />
    </html>
  )
}
